# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

include: "rules/common.smk"
configfile: "config.yaml"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        # SRA_fastq_for_download,
        # expand("Sample_Fastq/{sample}.fastq.gz", sample=SampleList),
        # expand( "Alignments/SecondPass/{sample}/SJ.out.annotated.tab", sample=SampleList),
        expand(config["gitinclude_output"] + "SJoutAnnotatedAndIntersected/{sample}.tab.gz", sample=SampleList)

include: "rules/other.smk"
include: "rules/DownloadAndMergeFastq.smk"
include: "rules/Align.smk"
